services:
  open-webui:
    image: ghcr.io/open-webui/open-webui:0.11.1
    container_name: open-webui
    restart: unless-stopped

    ports:
      - "${OPENWEBUI_PORT}:8080"

    environment:
      - WEBUI_SECRET_KEY=${WEBUI_SECRET_KEY}
      - OLLAMA_BASE_URL=${OLLAMA_BASE_URL}

      # Web Search
      - ENABLE_WEB_SEARCH=${ENABLE_WEB_SEARCH}
      
      - WEB_SEARCH_ENGINE=${WEB_SEARCH_ENGINE}
      - EXA_API_KEY=${EXA_API_KEY}
      - ENABLE_WEB_SEARCH_CONFIRMATION=false
      
      - OLLAMA_CONTEXT_LENGTH=${OLLAMA_CONTEXT_LENGTH}
      - DEFAULT_MODEL_METADATA=${DEFAULT_MODEL_METADATA}
      - DEFAULT_MODEL_PARAMS=${DEFAULT_MODEL_PARAMS}

    extra_hosts:
      - "host.docker.internal:host-gateway"

    volumes:
      - open-webui:/app/backend/data

volumes:
  open-webui:

networks:
  openwebui: