# ============================================================
# Help
# ============================================================

.PHONY: help

help:
	@printf "\n"
	@printf "🤖 Local AI Assistant\n"
	@printf "\n"
	@printf "🚀 Setup\n"
	@printf "  make setup                   Set up the complete environment\n"
	@printf "  make system-info             Show system and Ollama info\n"
	@printf "\n"
	@printf "🐳 Docker\n"
	@printf "  make docker-up               Start all services\n"
	@printf "  make docker-down             Stop all services\n"
	@printf "  make docker-restart          Restart all services\n"
	@printf "  make docker-status           Show service status\n"
	@printf "  make docker-logs             Show service logs\n"
	@printf "  make docker-clean-openwebui  Remove OpenWebUI only\n"
	@printf "  make docker-clean            Remove all Docker data ⚠️\n"
	@printf "\n"
	@printf "🦙 Ollama\n"
	@printf "  make ollama-start             Start Ollama\n"
	@printf "  make ollama-stop              Stop Ollama\n"
	@printf "  make ollama-download-models   Download configured models\n"
	@printf "  make ollama-info              Show Ollama status and models\n"
	@printf "\n"
	@printf "💬 OpenWebUI\n"
	@printf "  http://localhost:3000         Chat, agents, study and research\n"
	@printf "\n"
	@printf "💻 Continue\n"
	@printf "  VS Code extension             Local coding agents with Ollama\n"
	@printf "\n"
	@printf "⚙️  Configuration\n"
	@printf "  .env                          Customize project configuration\n"
	@printf "  .env.example                  Configuration template\n"
	@printf "\n"
	@printf "⚡ Quick start\n"
	@printf "  cp .env.example .env\n"
	@printf "  make setup\n"
	@printf "\n"