help:
	@printf "\n"
	@printf "🤖 Local LLM Assistant\n"
	@printf "\n"

	@printf "🚀 Setup\n"
	@printf "├── $(CLI_NAME) setup       Set up the complete environment\n"
	@printf "└── $(CLI_NAME) system-info Show system, hardware and Ollama info\n"
	@printf "\n"

	@printf "⚙️  CLI\n"
	@printf "├── $(CLI_NAME) install     Install the global CLI\n"
	@printf "└── $(CLI_NAME) uninstall   Remove the global CLI\n"
	@printf "\n"

	@printf "🐳 Docker\n"
	@printf "├── $(CLI_NAME) docker-up              Start all services\n"
	@printf "├── $(CLI_NAME) docker-down            Stop all services\n"
	@printf "├── $(CLI_NAME) docker-restart         Restart all services\n"
	@printf "├── $(CLI_NAME) docker-status          Show service status\n"
	@printf "├── $(CLI_NAME) docker-logs            Show service logs\n"
	@printf "├── $(CLI_NAME) docker-clean-openwebui Remove Open WebUI environment ⚠️\n"
	@printf "└── $(CLI_NAME) docker-clean           Remove Docker environment ⚠️\n"
	@printf "\n"

	@printf "🦙 Ollama\n"
	@printf "├── $(CLI_NAME) ollama                 Set up Ollama and configured models\n"
	@printf "├── $(CLI_NAME) ollama-install         Install / prepare Ollama\n"
	@printf "├── $(CLI_NAME) ollama-start           Start Ollama\n"
	@printf "├── $(CLI_NAME) ollama-stop            Stop Ollama\n"
	@printf "├── $(CLI_NAME) wait-ollama            Wait until Ollama is ready\n"
	@printf "├── $(CLI_NAME) ollama-download-models Download configured models\n"
	@printf "└── $(CLI_NAME) ollama-info            Show Ollama status and models\n"
	@printf "\n"

	@printf "💬 Open WebUI\n"
	@printf "└── http://localhost:$(OPENWEBUI_PORT)  Chat, files, knowledge, tools and agents\n"
	@printf "\n"

	@printf "💻 Continue\n"
	@printf "└── VS Code extension                    Coding, agents and project context\n"
	@printf "\n"

	@printf "🧹 Maintenance\n"
	@printf "└── $(CLI_NAME) teardown                 Remove the local AI environment ⚠️\n"
	@printf "\n"

	@printf "⚙️  Configuration\n"
	@printf "├── .env                                 Environment and service configuration\n"
	@printf "├── .env.example                         Configuration template\n"
	@printf "├── config/continue/config.yaml          Global Continue configuration\n"
	@printf "└── <Project>/.continue/                 Project-specific Continue configuration\n"
	@printf "\n"

	@printf "⚡ Quick start\n"
	@printf "├── First time (from repository)\n"
	@printf "│   ├── cp .env.example .env\n"
	@printf "│   └── make install\n"
	@printf "└── Then, from anywhere\n"
	@printf "    └── $(CLI_NAME) setup\n"
	@printf "\n"

	@printf "💡 CLI\n"
	@printf "   Run '$(CLI_NAME) <command>' from any directory.\n"
	@printf "   Inside the repository, 'make <command>' is also available.\n"
	@printf "\n"